# Generated by Django 4.1.4 on 2023-02-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_states'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='states',
            new_name='State',
        ),
    ]
