# Generated by Django 4.1.4 on 2023-04-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default=350, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user_email',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user_fisrt_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user_last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
