# Generated by Django 3.2.25 on 2024-08-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_order_status_order_user_email_order_user_fisrt_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pro_quantity',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
