# Generated by Django 4.1.4 on 2023-02-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_wishlist_product_id_alter_wishlist_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
