# Generated by Django 4.1.4 on 2023-02-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_wishlist_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='p_img',
            field=models.FileField(default=1, upload_to='wishlist/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_category',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_price',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
