# Generated by Django 4.1.4 on 2023-02-27 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_wishlist_p_img_wishlist_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product_id',
        ),
    ]
