# Generated by Django 4.1.4 on 2023-02-27 20:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_remove_wishlist_product_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlist',
            new_name='WishProduct',
        ),
    ]
