# Generated by Django 4.1.4 on 2023-03-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_wishlist_p_img_wishlist_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product_count',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
