# Generated by Django 4.1.4 on 2023-03-29 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_wishlist_product_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product_count',
        ),
    ]
